name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 21 # Adjust the Node.js version as needed
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Build
        env:
          BASE_PATH: '/thomasltran.github.io'
        run: yarn build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          target_branch: 'gh-pages'
          publish_dir: ./build
